<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>3de41be9-01c5-4401-8149-860b46e30f3d</UserSecretsId>
    </PropertyGroup>


    <ItemGroup>
        <PackageReference Include="Bogus" Version="35.6.5" />
        <PackageReference Include="FirebaseAdmin" Version="3.5.0" />
        <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
        <PackageReference Include="MailKit" Version="4.16.0" />
        <PackageReference Include="Mapster" Version="10.0.7" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.6" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.6" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.6" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.6" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.6">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.6" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.6">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.6" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.14.1" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
        <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.2" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Persistence\Migrations\" />
        <Folder Include="wwwroot\uploads\Categories\" />
        <Folder Include="wwwroot\uploads\Products\" />
    </ItemGroup>

    <ItemGroup>
        <_ContentIncludedByDefault Remove="wwwroot\Templates\EmailConfirmation.html" />
        <_ContentIncludedByDefault Remove="wwwroot\Templates\ForgetPassword.html" />
    </ItemGroup>

    <ItemGroup>
        <None Include="wwwroot\Templates\EmailConfirmation.html" />
        <None Include="wwwroot\Templates\ForgetPassword.html" />
    </ItemGroup>

</Project>
